title: "개발 블로그"
description: "공부 기록과 메모를 남기는 곳"
lang: ko-KR
timezone: Asia/Seoul

# 기본 설정
theme: minima
permalink: /:categories/:year/:month/:day/:title/

# 헤더/푸터 링크 (원하면 수정)
author:
  name: ""
  email: ""

minima:
  skin: auto
  social_links: []

# 빌드 시 제외할 파일/폴더
exclude:
  - node_modules
  - vendor
  - README.md
  - .github
  - .gitignore

# GitHub Pages에서 권장 옵션
markdown: kramdown
plugins: []

# 사이트 URL은 배포 후 원하면 설정
# url: "https://<your-username>.github.io"
# baseurl: ""

